app/__init__.py
from flask import Flask 
from app.routes import geogen_bp

def create_app():
    app = Flask(__name__)

    #enregistrer les blueprints
    app.register_blueprint(geogen_bp)

    return app

app/routes.py
# creation d'un blueprint
from flask import Blueprint, request, render_template
from app.services.geometrie import generer_motif
geogen_bp = Blueprint('geogen',__name__)

@geogen_bp.route('/')
def index(): 
    return render_template('index.html')

@geogen_bp.route('/generer_motif', methods=['POST'])
def generer_motif_route():
    try:
        #Récupérer les données envoyées par le formulaire
        cotes = int(request.form['cotes'])
        profondeur = int(request.form['profondeur'])
        taille = int(request.form['taille'])
        print(">> Taille reçue :", taille)
        angle_rotation = int(request.form['angle_rotation'])
        couleur = request.form['couleur']

        #Appeler la fonction generer_motif avec les paramètres reçus:
        fichier_image = generer_motif(cotes, profondeur, taille, angle_rotation, couleur)

        #Anciennement : Renvoie de l'image dans la balise img. Maintenant : Renvoie un template
        return render_template('generer_motif.html', chemin_image = fichier_image)
    
    except Exception as e: 
        #Gestion des errors; si une erreur se produit, on la stocke dans la variable e et on affiche un message personnalisé
        return f"Une_erreur_est_survenue : {str(e)}"

app/templates/generer_motif.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Résultat du motif</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <h1>Motif généré avec succès ! </h1>
    <img src="{{ url_for('static', filename=chemin_image ) }}" alt="Motif généré">
    <br> {# break <=> saut de ligne. Il n'y a pas besoin de fermer cette balise#}
    <a href="{{ url_for('geogen.index') }}"> Revenir à l'écran d'accueil</a>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Générateur de Motifs</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    
</head>
    <body>
        <div class="form-container">
            <h1> Générer un motif géométrique</h1> {#style="font-style:initial; color:brown; font-weight:500; text-decoration:underline ; text-align: center;#}
             <form action="/generer_motif" method="POST">
                <label> Nombre de côtés : </label>
                <input type= "number" name="cotes" required>
                <label>Profondeur ( répétitions ) : </label>
                <input type="number" name="profondeur" required>
                <label>Taille initiale:</label>
                <input type="number" name="taille" required min="10" max="500" step="10">
                <label> Angle de rotation : </label>
                <input type="number" name="angle_rotation" required>
                <label> Couleur : </label>
                <input type="color" name="couleur" value="#0000ff">  {#commentaire (fichier html) : modèle RVB #}
                
                <button type="submit">Générer</button>
            </form>
        </div>
    </body>
</html>